// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLvZJtwl8L_iwdO3xJU5qSTgLW9yuOMWc',
    appId: '1:79221638946:web:d434caea740924a628077b',
    messagingSenderId: '79221638946',
    projectId: 'wisata-db3c2',
    authDomain: 'wisata-db3c2.firebaseapp.com',
    storageBucket: 'wisata-db3c2.firebasestorage.app',
    measurementId: 'G-1HD4WTYFE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQSoKS9nJR5eWTL1_JgPSgT7bSOBgpxYY',
    appId: '1:79221638946:android:6453a949ce200ddd28077b',
    messagingSenderId: '79221638946',
    projectId: 'wisata-db3c2',
    storageBucket: 'wisata-db3c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqPyk6mWscPOhJAJra8QDYga_UVE1UB-c',
    appId: '1:79221638946:ios:75b7a435b46ba5f728077b',
    messagingSenderId: '79221638946',
    projectId: 'wisata-db3c2',
    storageBucket: 'wisata-db3c2.firebasestorage.app',
    iosBundleId: 'com.example.wisatajawa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqPyk6mWscPOhJAJra8QDYga_UVE1UB-c',
    appId: '1:79221638946:ios:75b7a435b46ba5f728077b',
    messagingSenderId: '79221638946',
    projectId: 'wisata-db3c2',
    storageBucket: 'wisata-db3c2.firebasestorage.app',
    iosBundleId: 'com.example.wisatajawa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLvZJtwl8L_iwdO3xJU5qSTgLW9yuOMWc',
    appId: '1:79221638946:web:d64993c9df38777028077b',
    messagingSenderId: '79221638946',
    projectId: 'wisata-db3c2',
    authDomain: 'wisata-db3c2.firebaseapp.com',
    storageBucket: 'wisata-db3c2.firebasestorage.app',
    measurementId: 'G-PH6540YRQ3',
  );
}
